Added all project requirement and fixed linter errors
Dagic-zewdu/rails-blog-app pull request #5
Opened 2022-06-08 18:54 UTC by Dagic-zewdu

- [ ] Create view for root and users#index
- [ ]  Create view for users#show
- [ ] Create view for posts#index
- [ ] Create view for posts#show

 Add basic styling

2022-06-08 19:36 UTC, DeliceLydia requested changes
## Hi @Dagic-zewdu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Highlights for your project are:
- No linter errors
- Followed git workflow


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-08 19:36 UTC, DeliceLydia commented on app/controllers/posts_controller.rb
> +  end
- [ ] I am not able to see a user post when I check user posts I am getting an error please address that:
![post](https://user-images.githubusercontent.com/44745855/172699520-0c9aef28-1436-4ebb-be92-a6aefb0ba34a.png)

2022-06-08 19:36 UTC, DeliceLydia commented on app/controllers/posts_controller.rb
> +  end
- [ ] Remember that you should render the user's 3 most recent post

2022-06-08 19:36 UTC, DeliceLydia commented on app/views/posts/_post_details.html.erb
> +      <span>Comment: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
- [ ] I am not able to create comments please address that
![post](https://user-images.githubusercontent.com/44745855/172701658-8c7736fe-8194-475e-830a-a7d17fdd5200.png)

2022-06-08 23:19 UTC, Gambit142 requested changes
Hi @Dagic-zewdu 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights

- Fixed views for Post controller. 👍 

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

#### I am making this suggestion here because I don't have access to the necessary file in the files changed section 👍 

- In your **_app/models/comment.rb_** file, your counter_cache should have the value of `comments_counter` and not `comments_count`. Also, in your `update_comments_count` function, kindly update `comments_counter` and not `comments_count.` 👍 

- In your **_app/models/like.rb_** file, your counter_cache should have the value of `likes_counter` and not `likes_count`. Also, in your `update_likes_count` function, kindly update `likes_counter` and not `likes_count.` 👍

#### The reason why I asked you to change them is that when I try to populate the database, I get errors due to those values. It would be nice to work on it and make your project function properly. 👍 

- Kindly check the comments under the review for other optional suggestions. 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 23:19 UTC, Gambit142 commented on app/views/users/show.html.erb
> +        <% end %>
- [ ] Great job implementing some changes based on the former reviewer' request. Please remember that the reviewer asked that you render a user's three most recent posts on the user#show page. Kindly implement it. `(@user_most_recent_three_posts)`. 👍

2022-06-08 23:19 UTC, Gambit142 commented on app/views/users/show.html.erb
> +  </button>
- [ ] (Optional) Remember that one of the project's requirements is that when you click the `See all posts` button it should link to the post#index page. It would be nice to implement it. 👍

2022-06-08 23:19 UTC, Gambit142 commented on app/views/users/_user.html.erb
> +  </div>
- [ ] (Optional) Remember that when you click a user, it should link you to the user#show page. It would be nice to implement it. 👍

2022-06-09 07:14 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Dagic-zewdu 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 07:49 UTC, merged