Added tests for the views
Dagic-zewdu/rails-blog-app pull request #9
Opened 2022-06-16 14:12 UTC by Dagic-zewdu

- Tests for Login page
- Tests for User index page
- Tests for user show page
- Tests for User post index page
- Tests for the Post-show page

2022-06-16 16:31 UTC, Deepakdanger requested changes
Hi @Dagic-zewdu & @muneebulrehman, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 

## Required Changes ♻️

- [ ] All your tests are failing. 

![Screenshot from 2022-06-16 21-49-49](https://user-images.githubusercontent.com/26767383/174118927-4bf28c03-0fae-4a77-9f5c-f175bf354f9a.png)

![Screenshot from 2022-06-16 21-50-01](https://user-images.githubusercontent.com/26767383/174118985-f28b6298-65a7-4100-827c-9bee84f3104b.png)

I think it's happening because of this error(attached below). Whatever we are giving data to **photo** column, they are trying to fetch in the asset pipeline. Because of this, we are unable to go to any of the pages. Please fix it.

![Screenshot from 2022-06-16 21-57-09](https://user-images.githubusercontent.com/26767383/174120306-51b6e678-f9ee-4e11-8eda-b8298194d7f6.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-17 15:29 UTC, julie-ify reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a Pull Request with failing linters

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-17 15:54 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

@Dagic-zewdu  ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___
### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [ ] Your branches' names are not descriptive. This is a [general](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Respect%20the%20rules%20of%20the%20code%20review%20flow%20that%20your%20team%20follows.%20Use%20descriptive%20names%20for%20your%20branches%20(e.g.%2C%20refactor%2Dauthentication%2C%20user%2Dcontent%2Dcache%2Dkey%2C%20make%2Dretina%2Davatars)%20and%20make%20sure%20that%20your%20%27feature%20branch%27%20is%20up%2Dto%2Ddate%20with%20the%20%27main%20branch%27%20in%20your%20repository.) rule for every project. Please pay attention to this in your next projects.

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-06-17 15:54 UTC, ahmetbozaci commented on spec/features/post_show_spec.rb .rb
> +end
- [ ] Kindly fix the error.

![image](https://user-images.githubusercontent.com/38635158/174333210-cf35a3f0-e6c8-468a-a523-d3d6173b55ef.png)

2022-06-17 15:54 UTC, ahmetbozaci commented on spec/features/user_index_spec.rb
> +end
- [ ] Kindly fix the error.
![image](https://user-images.githubusercontent.com/38635158/174333278-a3c866ec-2c6a-41ea-b719-15666a1c1833.png)

2022-06-17 15:54 UTC, ahmetbozaci commented on spec/features/user_show_spec.rb
> +end
- [ ] Kindly fix the error.

![image](https://user-images.githubusercontent.com/38635158/174333321-1451fb91-bc2b-461b-9324-0fdc0654461b.png)

2022-06-18 06:54 UTC, Mre55 approved these changes
**Hi @Dagic-zewdu,**

# Status: APPROVED 🏆 🎉 🎊 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

## To highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- All tests are passing ✅
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-20 08:44 UTC, merged